language: groovy
jdk:
  - oraclejdk8
install: gradle assemble
before_script:
  - "echo $JAVA_OPTS"
  - "export JAVA_OPTS=-Xmx512m"
script: gradle clean build test jacocoTestReport -s
notifications:
  email: false
branches:
  only:
    - master
env:
  global:
  - TERM=dumb
after_success:
  - bash <(curl -s https://codecov.io/bash)
